# Generated by Django 3.2.2 on 2021-05-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_rename_user_user_ex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vac_propria', models.BooleanField(default=False)),
                ('vac_pais', models.FloatField(default=25.0)),
                ('disponibilidade_quarentena', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='User_ex',
        ),
    ]
