# Generated by Django 3.2.2 on 2021-05-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_rename_user_name_profile_nome_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='nome_user',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
