# Generated by Django 3.2.2 on 2021-05-11 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_alter_profile_nome_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='disponibilidade_quarentena',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nome_user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='vac_pais',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='vac_propria',
        ),
    ]
