# Generated by Django 3.2.2 on 2021-05-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_auto_20210511_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='disponibilidade_quarentena',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='nome_user',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='vac_pais',
            field=models.FloatField(default=25.0),
        ),
        migrations.AddField(
            model_name='profile',
            name='vac_propria',
            field=models.BooleanField(default=False),
        ),
    ]
