# Generated by Django 3.1.7 on 2021-05-12 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_auto_20210512_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='vac_pais',
            field=models.FloatField(default=50.0),
        ),
    ]
