# Generated by Django 3.1.7 on 2021-05-17 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_auto_20210512_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nome_user',
        ),
    ]
