# Generated by Django 3.2.1 on 2021-05-25 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0011_alter_profile_id'),
        ('maps', '0011_remove_profile_nome_user'),
    ]

    operations = [
    ]
